// Product First Banner
export const PRODUCT_FIRST_BANNER_REQUEST = 'PRODUCT_FIRST_BANNER_REQUEST';
export const PRODUCT_FIRST_BANNER_SUCCESS = 'PRODUCT_FIRST_BANNER_SUCCESS';
export const PRODUCT_FIRST_BANNER_FAIL = 'PRODUCT_FIRST_BANNER_FAIL';

// Product Second Banner
export const PRODUCT_SECOND_BANNER_REQUEST = 'PRODUCT_SECOND_BANNER_REQUEST';
export const PRODUCT_SECOND_BANNER_SUCCESS = 'PRODUCT_SECOND_BANNER_SUCCESS';
export const PRODUCT_SECOND_BANNER_FAIL = 'PRODUCT_SECOND_BANNER_FAIL';

// Product List
export const PRODUCT_LIST_REQUEST = 'PRODUCT_LIST_REQUEST';
export const PRODUCT_LIST_SUCCESS = 'PRODUCT_LIST_SUCCESS';
export const PRODUCT_LIST_FAIL = 'PRODUCT_LIST_FAIL';

// Product Detail
export const PRODUCT_DETAIL_REQUEST = 'PRODUCT_DETAIL_REQUEST';
export const PRODUCT_DETAIL_SUCCESS = 'PRODUCT_DETAIL_SUCCESS';
export const PRODUCT_DETAIL_FAIL = 'PRODUCT_DETAIL_FAIL';

// Product Review
export const PRODUCT_REVIEW_ADD_REQUEST = 'PRODUCT_REVIEW_ADD_REQUEST';
export const PRODUCT_REVIEW_ADD_SUCCESS = 'PRODUCT_REVIEW_ADD_SUCCESS';
export const PRODUCT_REVIEW_ADD_FAIL = 'PRODUCT_REVIEW_ADD_FAIL';
