// Product First Banner
export const PRODUCT_FIRST_BANNER_REQUEST = 'PRODUCT_FIRST_BANNER_REQUEST';
export const PRODUCT_FIRST_BANNER_SUCCESS = 'PRODUCT_FIRST_BANNER_SUCCESS';
export const PRODUCT_FIRST_BANNER_FAIL = 'PRODUCT_FIRST_BANNER_FAIL';

// Product Second Banner
export const PRODUCT_SECOND_BANNER_REQUEST = 'PRODUCT_SECOND_BANNER_REQUEST';
export const PRODUCT_SECOND_BANNER_SUCCESS = 'PRODUCT_SECOND_BANNER_SUCCESS';
export const PRODUCT_SECOND_BANNER_FAIL = 'PRODUCT_SECOND_BANNER_FAIL';

// Product List
export const PRODUCT_LIST_REQUEST = 'PRODUCT_LIST_REQUEST';
export const PRODUCT_LIST_SUCCESS = 'PRODUCT_LIST_SUCCESS';
export const PRODUCT_LIST_FAIL = 'PRODUCT_LIST_FAIL';
