export const USER_ACCESS_REQUEST = 'USER_ACCESS_REQUEST';
export const USER_ACCESS_SUCCESS = 'USER_ACCESS_SUCCESS';
export const USER_ACCESS_FAIL = 'USER_ACCESS_FAIL';

export const USER_EXIT = 'USER_EXIT';
